apiVersion: v1
kind: Service
metadata:
  name: jenkins
  labels:
    app: jenkins
    service: devops
spec:
  type: LoadBalancer
  ports:
    - name: 8080-http
      port: 8080
      targetPort: 8080
    - name: 50000-http
      port: 50000
      targetPort: 50000
  selector:
    app: jenkins
    service: devops