FROM terrysxu/jenkins
COPY plugins.txt /usr/share/jenkins/ref/
RUN /usr/local/bin/install-plugins.sh < /usr/share/jenkins/ref/plugins.txt

ARG user=jenkins
ARG group=jenkins
ARG uid=1000
ARG gid=1000
ARG nexus_port=8081
ARG SONARQUBE_HOME=/var/sonarqube_home
ARG NEXUS_HOME=/var/nexus_home
EXPOSE ${nexus_port}

USER root


RUN mkdir -p $NEXUS_HOME \
  && chown ${uid}:${gid} $NEXUS_HOME 
    
RUN mkdir -p /usr/share/nexus
  
#ARG NEXUS_URL=https://download.sonatype.com/nexus/oss/nexus-2.14.11-01-bundle.tar.gz
COPY nexus-2.14.12-02-bundle.tar.gz /usr/share/nexus/nexus-2.14.12-02-bundle.tar.gz
#RUN curl -fsSL ${NEXUS_URL} -o /usr/share/nexus/nexus-2.14.11-01-bundle.tar.gz

RUN tar -xzvf /usr/share/nexus/nexus-2.14.12-02-bundle.tar.gz  -C /usr/share/nexus/
RUN chown -R ${user}:${user} /usr/share/nexus
RUN chmod +x /usr/share/nexus/nexus-2.14.12-02/bin/nexus
COPY jenkins.sh /usr/local/bin/jenkins.sh
RUN chmod +x /usr/local/bin/jenkins.sh



RUN groupadd sonarqube \
  && useradd sonarqube -g sonarqube

RUN mkdir -p $SONARQUBE_HOME \
  && chown sonarqube:sonarqube $SONARQUBE_HOME

RUN mkdir -p /usr/share/sonarqube

ARG SONARQUBE_URL=https://binaries.sonarsource.com/Distribution/sonarqube/sonarqube-7.8.zip
#RUN curl -fsSL ${SONARQUBE_URL} -o /usr/share/sonarqube/sonarqube-7.8.zip
COPY sonarqube-7.8.zip /usr/share/sonarqube/
RUN unzip -o /usr/share/sonarqube/sonarqube-7.8.zip -d /usr/share/sonarqube/
RUN chown -R sonarqube:sonarqube /usr/share/sonarqube
RUN chmod +x /usr/share/sonarqube/sonarqube-7.8


#USER ${user}

#ENTRYPOINT ["/sbin/tini", "--", "/usr/local/bin/jenkins.sh"]

#CMD ["/usr/share/nexus/nexus-professional-2.14.12-02/bin/nexus", "start"]




