apiVersion: v1
kind: Service
metadata:
  name: nexus
  labels:
    app: nexus
    service: devops
spec:
  type: LoadBalancer
  ports:
    - name: 8081-http
      port: 8081
      targetPort: 8081
  selector:
    app: nexus
    service: devops