apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.jenkins.name }}
  labels:
    app: {{ .Values.jenkins.name }}
    service: {{ include "devops.name" . }}
    {{- include "devops.labels" . | nindent 4 }}    
type: Opaque
stringData:
  jenkins_user: {{ .Values.tapd.jenkins_user }}
  jenkins_user_password: {{ .Values.tapd.jenkins_user_password }}