apiVersion: v1
kind: ConfigMap
metadata:
  name: "{{ .Values.jenkins.name }}-config"
  labels:
    app: {{ .Values.jenkins.name }}
    service: {{ include "devops.name" . }}
    {{- include "devops.labels" . | nindent 4 }}
data:
  apply_config.sh: |-
    echo "remove all plugins from shared volume"
    rm -rf /var/jenkins_home/plugins/*
    rm -rf /usr/share/jenkins/ref/plugins/*

    echo "download tapd plugin"
    curl -sSfL --connect-timeout 20 --retry 3 --retry-delay 0 --retry-max-time 60 https://test-1251542635.cos.ap-guangzhou.myqcloud.com/TapdPipeLine.jpi -o /usr/share/jenkins/ref/plugins/TapdPipeLine.jpi

    echo "download plugins"
    # Install missing plugins
    cp /var/jenkins_config/plugins.txt /var/jenkins_home;
    
    version () { echo "$@" | awk -F. '{ printf("%d%03d%03d%03d\n", $1,$2,$3,$4); }'; }
    if [ -f "/usr/share/jenkins/jenkins.war" ] && [ -n "$(command -v jenkins-plugin-cli)" 2>/dev/null ] && [ $(version $(jenkins-plugin-cli --version)) -ge $(version "2.1.1") ]; then
      jenkins-plugin-cli --verbose --war "/usr/share/jenkins/jenkins.war" --plugin-file "/var/jenkins_home/plugins.txt";
    else
      /usr/local/bin/install-plugins.sh `echo $(cat /var/jenkins_home/plugins.txt)`;
    fi
    echo "copy plugins to shared volume"
    yes n | cp -i /usr/share/jenkins/ref/plugins/* /var/jenkins_plugins/;
    echo "finished initialization"
  plugins.txt: |-
    matrix-auth
    sonar
    nexus-jenkins-plugin
    credentials
    plain-credentials
    workflow-aggregator
    pipeline-graph-analysis
    script-security
    scm-api
    git
    subversion