apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.jenkins.name }}
  labels:
    app: {{ .Values.jenkins.name }}
    service: {{ include "devops.name" . }}
    {{- include "devops.labels" . | nindent 4 }}
spec:
  type: {{ .Values.jenkins.service.type }}
  ports:
    - name: {{ .Values.jenkins.service.port }}-http
      port: 8080
      targetPort: {{ .Values.jenkins.service.port }}
    - name: {{ .Values.jenkins.service.agentport }}-http
      port: 50000
      targetPort: {{ .Values.jenkins.service.agentport }}
  selector:
    app: {{ .Values.jenkins.name }}
    service: {{ include "devops.name" . }}
    {{- include "devops.selectorLabels" . | nindent 4 }}     