apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.nexus.name }}
  labels:
    app: {{ .Values.nexus.name }}
    service: {{ include "devops.name" . }}
    {{- include "devops.labels" . | nindent 4 }}
spec:
  {{- if not .Values.nexus.autoscaling.enabled }}
  replicas: {{ .Values.nexus.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      app: {{ .Values.nexus.name }}
      service: {{ include "devops.name" . }}
      {{- include "devops.selectorLabels" . | nindent 6 }}      
  template:
    metadata:
      name: {{ .Values.nexus.name }}
      {{- with .Values.nexus.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        app: {{ .Values.nexus.name }}
        service: {{ include "devops.name" . }}
        {{- include "devops.selectorLabels" . | nindent 8 }}         
    spec:
      initContainers:
        - name: kona-jdk-init
          image: ccr.ccs.tencentyun.com/tapd-devops/tencentkona8-tlinux:latest
          imagePullPolicy: {{ .Values.nexus.image.pullPolicy }}
          command: ["cp", "-r", "/opt/jdk", "/kona"]
          volumeMounts:
            - name: kona-java-home
              mountPath: /kona
      containers:
        - name: nexus
          image: "{{ .Values.nexus.image.repository | default "sonatype/nexus3" }}:{{ .Values.nexus.image.tag | default "3.38.1" }}"
          imagePullPolicy: {{ .Values.nexus.image.pullPolicy }}
          securityContext:
            {{- toYaml .Values.nexus.securityContext | nindent 12 }}        
          env:
            - name: TZ
              value: Asia/Shanghai
            - name: LANG
              value: C.UTF-8
            - name: LANGUAGE
              value: C.UTF-8
            - name: LC_ALL
              value: C.UTF-8
            - name: INSTALL4J_JAVA_HOME_OVERRIDE
              value: /opt/java/jdk
            - name: INSTALL4J_ADD_VM_PARAMS
              value: |-
                -Xms2703M -Xmx2703M
                -XX:MaxDirectMemorySize=2703M
                -XX:+UnlockExperimentalVMOptions
                -XX:+UseCGroupMemoryLimitForHeap
                -Djava.util.prefs.userRoot=/nexus-data/javaprefs
          ports:
            - name: 8081-http
              containerPort: 8081
          livenessProbe:
            httpGet:
              path: /
              port: 8081-http
            initialDelaySeconds: 30
            periodSeconds: 30
            failureThreshold: 6
            timeoutSeconds: 10
          readinessProbe:
            httpGet:
              path: /
              port: 8081-http
            initialDelaySeconds: 30
            periodSeconds: 30
            failureThreshold: 6
            timeoutSeconds: 10
          volumeMounts:
            - name: nexus-data
              mountPath: /nexus-data
            - name: kona-java-home
              mountPath: /opt/java
          resources:
            {{- toYaml .Values.nexus.resources | nindent 12 }}          
      volumes:
        - name: nexus-data
          emptyDir: {}
        - name: kona-java-home
          emptyDir: {}
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "devops.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.nexus.podSecurityContext | nindent 8 }}        
      {{- with .Values.nexus.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.nexus.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.nexus.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
