apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.nexus.name }}
  labels:
    app: {{ .Values.nexus.name }}
    service: {{ include "devops.name" . }}
    {{- include "devops.labels" . | nindent 4 }}    
type: Opaque
stringData:
  nexus_user: {{ .Values.tapd.nexus_user }}
  nexus_user_password: {{ .Values.tapd.nexus_user_password }}