apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.sonarqube.name }}
  labels:
    app: {{ .Values.sonarqube.name }}
    service: {{ include "devops.name" . }}
    {{- include "devops.labels" . | nindent 4 }}    
spec:
  type: {{ .Values.sonarqube.service.type }}
  ports:
    - name: {{ .Values.sonarqube.service.port }}-http
      port: 9000
      targetPort: {{ .Values.sonarqube.service.port }}
  selector:
    app: {{ .Values.sonarqube.name }}
    service: {{ include "devops.name" . }}
    {{- include "devops.selectorLabels" . | nindent 4 }}