apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.sonarqube.name }}
  labels:
    app: {{ .Values.sonarqube.name }}
    service: {{ include "devops.name" . }}
    {{- include "devops.labels" . | nindent 4 }}    
type: Opaque
stringData:
  sonarqube_user: {{ .Values.tapd.sonarqube_user }}
  sonarqube_user_password: {{ .Values.tapd.sonarqube_user_password }}